### ISSUE TITLE
3030000 tx_missing_posting_auth: missing required posting authority

### ISSUE THREAD

**Issue by SergeyGoryainov** [t3ran13/php-graphene-node-client#10]
Добрый день!

Пытаюсь использовать библиотеку, но при попытке проголосовать возникает ошибка 3030000 tx_missing_posting_auth: missing required posting authority.

Брал пример из других веток с вопросами:
`$connector = new SteemitHttpConnector();
$answer = OpVote::doSynchronous(
$connector,
'guest123',
'5JRaypasxMx1L97ZUX7YuC5Psb5EAbF821kkAGtBj7xCJFQcbLg',
't3ran13',
'color-world-magic-prague-12-cute-place-panorama',
10000
);`

При попытке проголосовать приходит ошибка в файле
File:
/var/www/steemit.local/httpd/vendor/fguillot/json-rpc/src/JsonRPC/Response/ResponseParser.php:135

с сообщением:
`3030000 tx_missing_posting_auth: missing required posting authority
Missing Posting Authority guest123
    {"id":"guest123","posting":{"weight_threshold":1,"account_auths":[["busy.app",1]],"key_auths":[["STM6aGPtxMUGnTPfKLSxdwCHbximSJxzrRjeQmwRW9BRCdrFotKLs",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7KVz2JzGVUHuuguoAK9BPosAbXWaCEp3Bgr5TUmMyvPjSJRt6m",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5j6x515jjYcjqtSVr7c6FRaXMkUGUDdduxvQJ3M1abDYxiT7Lx",1]]}}
    th_a  transaction.cpp:129 verify_authority

    {"ops":[["vote",{"voter":"guest123","author":"t3ran13","permlink":"color-world-magic-prague-12-cute-place-panorama","weight":10000}]],"sigs":["STM5Qoz69koekZQkjHknGM6YJ8th1DfXn57ea2QMkr7x6vxqYAkUT"]}
    th_a  transaction.cpp:172 verify_authority

    {"*this":{"ref_block_num":37976,"ref_block_prefix":792081596,"expiration":"2018-03-10T10:40:24","operations":[["vote",{"voter":"guest123","author":"t3ran13","permlink":"color-world-magic-prague-12-cute-place-panorama","weight":10000}]],"extensions":[],"signatures":["201941c1eadb0b11642849fffe13a7df2232b3c21ca1c812d8383532bd8df88bec522609b7e2b44e4b4802ac499c67171dcd828b9707e4171347e094a5b48f1d8e"]}}
    th_a  transaction.cpp:285 verify_authority

    {"trx":{"ref_block_num":37976,"ref_block_prefix":792081596,"expiration":"2018-03-10T10:40:24","operations":[["vote",{"voter":"guest123","author":"t3ran13","permlink":"color-world-magic-prague-12-cute-place-panorama","weight":10000}]],"extensions":[],"signatures":["201941c1eadb0b11642849fffe13a7df2232b3c21ca1c812d8383532bd8df88bec522609b7e2b44e4b4802ac499c67171dcd828b9707e4171347e094a5b48f1d8e"]}}
    th_a  database.cpp:2897 _apply_transaction

    {"trx":{"ref_block_num":37976,"ref_block_prefix":792081596,"expiration":"2018-03-10T10:40:24","operations":[["vote",{"voter":"guest123","author":"t3ran13","permlink":"color-world-magic-prague-12-cute-place-panorama","weight":10000}]],"extensions":[],"signatures":["201941c1eadb0b11642849fffe13a7df2232b3c21ca1c812d8383532bd8df88bec522609b7e2b44e4b4802ac499c67171dcd828b9707e4171347e094a5b48f1d8e"]}}
    th_a  database.cpp:660 push_transaction

    {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"ref_block_num":37976,"ref_block_prefix":792081596,"expiration":"2018-03-10T10:40:24.000","operations":[["vote",{"voter":"guest123","author":"t3ran13","permlink":"color-world-magic-prague-12-cute-place-panorama","weight":10000}]],"extensions":[],"signatures":["201941c1eadb0b11642849fffe13a7df2232b3c21ca1c812d8383532bd8df88bec522609b7e2b44e4b4802ac499c67171dcd828b9707e4171347e094a5b48f1d8e"]}]]}
    th_a  websocket_api.cpp:124 on_message`

Выполнял [docker файл](https://github.com/t3ran13/php-graphene-node-client/blob/debug/docker/local/dockerfile-php7-fpm), но не помогло. Также находил статью [в Голосе](https://golos.io/ru--otkrytyij-kod/@php-node-client/ispravlena-kriticheskaya-oshibka-v-broadcast-php-graphene-node-client-v3-1-1), но обновление не исправило ошибки.

В [ветке](https://github.com/t3ran13/php-graphene-node-client/issues/7) было написано использовать ноду https://api.steemit.com и что с ней голосование работает, SteemitHttpConnector использует её, но проголосовать не получается.

Может быть я что-то упускаю? Не могли бы вы подсказать, что еще можно проверить?

**Comment by SergeyML1000** [comment]
Здравствуйте.
Такая же проблема

**Comment by t3ran13** [comment]
апвоты работают для https://steemd.privex.io
к https://api.steemit.com подключиться не вышло, чет она тупит долго, видимо загружена

рекомендую сохранить к себе страничку с нодами стима
https://www.steem.center/index.php?title=Public_Websocket_Servers

там под табличкой две ссылки
- на хттп ноды и их статусы https://geo.steem.pl/
- тоже самое для ws нод http://steemistry.com/nodes/

вообще ноды ложаться часто. потому в коннекторе предусмотрено два параметра

```php
    /**
     * max number of tries to get answer from the node
     *
     * @var int
     */
    protected $maxNumberOfTriesToCallApi = 3;


    /**
     * https or http server
     *
     * if you set several nodes urls, if with first node will be trouble
     * it will connect after $maxNumberOfTriesToCallApi tries to next node
     *
     * @var string
     */
    protected $nodeURL = ['https://steemd.privex.io'];

```
в последнем можете указать несколько нод
но помните, не во всех публичных нодах включены все плагины, потому некоторые данные, типа репутации пользователей, могут не соотвествовать действительности.

**Comment by t3ran13** [comment]
@SergeyGoryainov 
"missing required posting authority" - ошибка вообще из-за того, что транзакция неправильно приготовлена, но если юзаете докер файл, то проблем быть не должно, там все необходимое устанавливается

потому попробуйте другие ноды

**Comment by t3ran13** [comment]
саму либу ставите через композер?

**Comment by SergeyGoryainov** [comment]
@t3ran13 Да, через композер. Пробовал переустанавливать всё с нуля, пробовал разные ноды, но никаких изменений. Можно ли как-то с вами созвониться/списаться, чтобы вы меня проконсультировали по поводу этой ошибки. Видимо, я что-то не так делаю, но не могу выяснить в чём проблема. За потраченное ваше время я бы заплатил. Если это возможно, напишите мне на почту sergeygr@ml1000.net.

**Comment by t3ran13** [comment]
@SergeyGoryainov 
@SergeyGoryainov 

отловил багу, оказывается ошибка была в сериализации строк. В результате все работало только для коротких значений

фикс лежит в мастере

**Comment by t3ran13** [comment]
закройте если все гуд
