### ISSUE TITLE
v.4.0: syntax error, unexpected 'do' (T_DO)

### ISSUE THREAD

**Issue by jackvote** [t3ran13/php-graphene-node-client#13]
Эксперементирую с библиотекой. С утра собрал composer с v4.0

$command = new GetAccountCountCommand($client);
$answer = $command->execute($commandQuery);
Чтение благополучно сработало.

Пытаюсь апнуть пост на Голосе

Parse error: syntax error, unexpected 'do' (T_DO), expecting identifier (T_STRING) in /home/public_html/test/vendor/t3ran13/php-graphene-node-client/Tools/ChainOperations/OpVote.php on line 25

Взято из примера

```
<?php
// подключение библиотеки
require('vendor/autoload.php');

use GrapheneNodeClient\Tools\ChainOperations\OpVote;
use GrapheneNodeClient\Tools\ChainOperations\OpComment;
//use GrapheneNodeClient\Connectors\Http\SteemitHttpConnector;
use GrapheneNodeClient\Connectors\WebSocket\GolosWSConnector;

//$connector = new SteemitHttpConnector();
$connector = new GolosWSConnector();

$answer = OpVote::doSynchronous(
    $connector,
    'jackvote',
    '5KQwg3XDkSEYMxXKjbeKuRuySKvBqFn4k3eo3tmMpxV2v4WysRn',
    'svetoruss',
    'ns95p-veselye-kartinki',
    10000
);
print_r($answer);
// example of answer
//Array
//(
//    [id] => 5
//    [result] => Array
//        (
//            [id] => a2c52988ea870e446480782ff046994de2666e0d
//            [block_num] => 17852337
//            [trx_num] => 1
//            [expired] =>
//        )
//
//)

?>
```

**Comment by t3ran13** [comment]
Приватником своим не свети

**Comment by t3ran13** [comment]
Я для тестов создал guest123, юзай его

Гляну вечером и отвечу

**Comment by jackvote** [comment]
Там буковки-циферки поменяны. :-)
Про guest123 не понял. В смысле к нему тестовые комменты постить и апать?

**Comment by t3ran13** [comment]
https://github.com/t3ran13/php-graphene-node-client/blob/debug/Debug/Test.php
глянь там пароли для стима и голоса)

**Comment by t3ran13** [comment]
а какая версия пхп?

**Comment by jackvote** [comment]
PHP Version 5.4.45
http://expertgroup.org/test/pi.php

**Comment by jackvote** [comment]
В целом хостинг на: 

Версия Apache | 2.2.31
Версия PHP | 5.3.29
Версия MySQL | 10.1.32-MariaDB

Можно выставить любую версию php через
AddType application/x-httpd-ph54-fcgi .php

**Comment by t3ran13** [comment]
В требовпниях минимум 5.4 вродь. Глянь сомпозер jsob

**Comment by t3ran13** [comment]
перепроверил, такой баг не нашел, нашел другие=)
как будто нельзя использовать имя метода do
попробуйте букву к do в OpVote.php  добавить в либе напрямую
я тестирую на php 7.1 и проблем нет никаких)

**Comment by jackvote** [comment]
Так 5.4 и стоит. К сожалению, на хостингах не любят до последних обновляться.

К функции?
public static function **dmo**(ConnectorInterface $connector, $voter, $publicWif, $author, $permlink, $weight)
Тогда
Fatal error: Arrays are not allowed in class constants in /home/public_html/addsites/expertgroup/test/vendor/t3ran13/php-graphene-node-client/Tools/Transaction.php on line 23

**Comment by jackvote** [comment]
Так выставил PHP Version 7.1.11
http://expertgroup.org/test/pi.php
Вообще скрипт не отзывается.
Завтра попробую debug/Debug/Test.php скопировать, поэксперементировать.

**Comment by t3ran13** [comment]
хм... попробую поганять по разным версиям php начиная от 5.4. завтра

**Comment by t3ran13** [comment]
в докере не стала зависимость secp256k1 для php 5.6, потому поправил версию php на 7
для 7.0 и 7.1 все работает)

**Comment by t3ran13** [comment]
там в ветке debug есть докер, попробуйте локально его развернуть и в нем запуститьь пример) потом можно весь процесс установки компонентов глянуть в докерфайле

**Comment by jackvote** [comment]
Хорошо. Попробую. Ещё бы понять, что это и под какой сОСусой его употреблять. :-)
Так понимаю, докер - виртуалка. На хостинг вряд ли смогу взгромоздить. А на компе винда.

**Comment by t3ran13** [comment]
Он под винду есть
На хостинге у вас чет странное

**Comment by t3ran13** [comment]
Аа, вы на хостинге либы нужные для отправки транзакций не поставите никак

**Comment by t3ran13** [comment]
Т.е. компоненты системы, нужные для либ

**Comment by jackvote** [comment]
Вот ведь засада-то. :-\
А я считал, что это независимый клиент. Собирает через composer всё необходимое.
Хм, ну, на практике у меня есть доступ к хостингу через ssh. Вопрос, смогу ли я туда какие-то бибилиотеки установить и как потом к ним путь прописывать.

**Comment by t3ran13** [comment]
)))) подходящий момент чб почитать ридми

**Comment by jackvote** [comment]
Ещё бы он на русском был написан.

**Comment by t3ran13** [comment]
Понял, в дебагере есть докерфайл, в нем ставится все необходимое на шинукс для транзакций, кроме пхп. Сделай как там и все должно работать.

Либо постига докер

**Comment by denis-skripnik** [comment]
> Понял, в дебагере есть докерфайл, в нем ставится все необходимое на шинукс для транзакций, кроме пхп. Сделай как там и все должно работать.

А где этот дебагер и докерфайл? Что-то на github не нахожу ни того, не другого. И как ставить php в докер, не прогадав с образом? Ведь можно поставить не туда, где находится всё необходимое для транзакций.
И как дела обстоят с Cron: хочу запустить мониторинг данных и выполнение действий без веб-интерфейсов, но как с Кроном в Docker не знаю.

**Comment by t3ran13** [comment]
В докере с кроном норма

Докер файл искать в ветке debug
