### ISSUE TITLE
Call to undefined function GrapheneNodeClient\Tools\secp256k1_context_create()

### ISSUE THREAD

**Issue by milanamatya** [t3ran13/php-graphene-node-client#16]

**Comment by t3ran13** [comment]
Read intall ib readme
You have to install extensions for php

**Comment by milanamatya** [comment]
how do i install https://github.com/Bit-Wasp/secp256k1-php on windows ?

**Comment by t3ran13** [comment]
Use docker, vagrant or vm-ware

**Comment by milanamatya** [comment]
i installed all components and extensions, but while 
echo "extension=secp256k1.so" > /usr/local/etc/php/conf.d/secp256k1.ini

error says,
-bash: /usr/local/etc/php/conf.d/secp256k1.ini: No such file or directory

**Comment by milanamatya** [comment]
now another error saying 
Argument 2 passed to secp256k1_ecdsa_recoverable_signature_serialize_compact() must be of the type string or null, resource given

**Comment by t3ran13** [comment]
See install section in readme and sure that you installed correct lib

**Comment by milanamatya** [comment]
I think you have error in code.

**Comment by milanamatya** [comment]
I succesfully corrected and now working with  changes in Transaction.pho, signOperation function

**Comment by milanamatya** [comment]
protected static function signOperation($msg, $privateWif)
    {
        $context = secp256k1_context_create(SECP256K1_CONTEXT_SIGN | SECP256K1_CONTEXT_VERIFY);

        $msg32 = hash('sha256', hex2bin($msg), true);
        $privateKey = Auth::PrivateKeyFromWif($privateWif);

        /** @var resource $signature */
        $signatureRec = null;
        $i = 0;
        while (true) {
            if ($i === 1) {
                //sing always the same
                throw new TransactionSignException("Can't to find canonical signature, {$i} ties");
            }
            $i++;
//            echo "\n i=" . print_r($i, true) . '<pre>'; //FIXME delete it
            if (secp256k1_ecdsa_sign_recoverable($context, $signatureRec, $msg32, $privateKey) !== 1) {
                throw new TransactionSignException("Failed to create recoverable signature");
            }

            $signature = null;
            if (secp256k1_ecdsa_recoverable_signature_convert($context, $signature, $signatureRec) !== 1) {
                throw new TransactionSignException("Failed to create signature");
            }
            $der = null;
            if (secp256k1_ecdsa_signature_serialize_der($context, $der, $signature) !== 1) {
                throw new TransactionSignException("Failed to create DER");
            }
//            echo "\n" . print_r(bin2hex($der), true) . '<pre>'; //FIXME delete it
            if (self::isSignatureCanonical($der)) {
                break;
            }
        }

        $serializedSig = null;
        $recid = 0;
        secp256k1_ecdsa_recoverable_signature_serialize_compact($context, $serializedSig, $recid,$signatureRec);

        $serializedSig = hex2bin(base_convert($recid + 4 + 27, 10, 16)) . $serializedSig;
        $length = strlen($serializedSig);
        if ($length !== 65) {
            throw new \Exception('Expecting 65 bytes for Tx signature, instead got ' . $length);
        }

        return bin2hex($serializedSig);
    }

**Comment by milanamatya** [comment]
Please check the pull request i have submitted.

**Comment by t3ran13** [comment]
ok, use https://github.com/Bit-Wasp/secp256k1-php/releases/tag/v0.1.2 for correct working
or you can wait while i will up Bit-Wasp/secp256k1-php to  v0.2.1

**Comment by t3ran13** [comment]
i fixed it
v5.0.1

**Comment by milanamatya** [comment]
you didnt mentioned me in your post in steemit, my steemit account @milan.amatya13

**Comment by t3ran13** [comment]
done, make post for utopian.io
