### ISSUE TITLE
Alternative To Secp256k1 Needing Installed

### ISSUE THREAD

**Issue by cadawg** [t3ran13/php-graphene-node-client#24]
So many web servers don't let you install Secp256k1 on them, so I've done some research and found these libraries which can do it natively:

https://github.com/simplito/elliptic-php

https://github.com/phpecc/phpecc

I had a look at the code, and it's too complex for me, but I was wondering if it'd be possible to support it in this library, as it would mean I could use it in my projects.

**Comment by t3ran13** [comment]
the first one give the same sign for different msg - it is not secure

**Comment by t3ran13** [comment]
the first is great
https://github.com/simplito/elliptic-php

done, see release 6.0.0

**Comment by cadawg** [comment]
YAY! Thanks @t3ran13, I can finally use this library! ❤❤❤

**Comment by t3ran13** [comment]
you are welcome!
