### ISSUE TITLE
Transaction sign fails when using not-latin symbols in title or body

### ISSUE THREAD

**Issue by norbis** [t3ran13/php-graphene-node-client#8]
Hi,
trying send post to blockchain and transaction sign fail when using non-latin chars in title or body.
This code works:
     
        $strPermlink = '...Post perm link...';
        $strAuthor = '...Account...';
        $strPostingWif = '...Private posting wif...';
        $strMainTag = '...Main tag...';
        $connector = new GolosWSConnector();
        $answer = OpComment::doSynchronous(
            $connector,
            $strPostingWif,
            $strAuthor,
            $strPermlink,
            'Post test title',
            'Post test body',
            json_encode([
                'tags' => ['golos'],
                'format' => 'markdown',
            ]),
            $strMainTag,
            ''
        );

But this code not works: 

        $strPermlink = '...Post perm link...';
        $strAuthor = '...Account...';
        $strPostingWif = '...Private posting wif...';
        $strMainTag = '...Main tag...';
        $connector = new GolosWSConnector();
        $answer = OpComment::doSynchronous(
            $connector,
            $strPostingWif,
            $strAuthor,
            $strPermlink,
            'Русский',
            'Post test body',
            json_encode([
                'tags' => ['golos'],
                'format' => 'markdown',
            ]),
            $strMainTag,
            ''
        );

With error: "3030000 tx_missing_posting_auth: missing required posting authority"

**Comment by t3ran13** [comment]
fixed
use v3.1.1
